version: '3.8'
services:
  docusaurus:
    image: node:lts
    working_dir: /opt/docusaurus
    volumes:
      - .:/opt/docusaurus  # Mount the project folder for live reloading
    ports:
      - "3000:3000"
    command: >
      /bin/sh -c "npm install && npm run start -- --host 0.0.0.0"
